version: '3.8'
services:
  test-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: token_manager_test
    ports:
      - '5433:5432'
    volumes:
      - test_db_data:/var/lib/postgresql/data

  test-app:
    build: .
    environment:
      DATABASE_URL: postgresql://user:password@test-db:5432/token_manager_test
      NODE_ENV: test
    ports:
      - '3001:3000'
    volumes:
      - .:/app
    command: sh -c "npx prisma generate && npx prisma db push && npm run prisma:seed && npm run dev"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - test-db
    restart: always

volumes:
  test_db_data:
