version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: token_manager_db
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/token_manager_db
    ports:
      - '${APP_PORT:-3000}:3000'
    volumes:
      - .:/app
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"
    restart: always
  app-dev:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/token_manager_db
    ports:
      - '${APP_DEV_PORT:-3001}:3000'
    volumes:
      - .:/app
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"
    restart: always
volumes:
  db_data:
